app = "ghost-of-cdc"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
URL = "atypicallife.club"

[experimental]
auto_rollback = true

[scaling]
min = 1 # 最小实例数
max = 3 # 最大实例数

[[services]]
internal_port = 2368
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "30s"
interval = "15s"
timeout = "2s"
